### ISSUE TITLE
Add a button to the pictures for fullscreen.

### ISSUE THREAD

**Issue by faishal** [rtMediaWP/rtMedia#517] opened 2014-02-26 05:19 UTC
If you have galleries you want to see a picture in fullscreen without the comment section for a better user experience. 

https://rtcamp.com/rtmedia/docs/common/shortcodes/gallery-shortcode/#comment-115269

**Comment by kjnanda** [comment] 2019-11-22 12:56
We have already added this in our Ac task To-Do.  

Also, Duplicate of - #1064

**Closed by kjnanda** 2019-11-22 12:56 UTC
