### ISSUE TITLE
[Upload terms checkbox] Issue list when direct upload and upload terms kept enabled together

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1292] opened 2019-03-01 10:55 UTC
Please check my comment below.

- [ ] 1.

## ~~Scenario 1 - First add some text and click on upload terms checkbox~~ 

It is not giving me time to upload the media as soon as I click on `upload terms` it posts the text area content.

Please refer this link for visual - https://goo.gl/13XtLf

-----

- [ ] 2.

## Scenario 2 - First upload some media and then try to enter some text in text area

Text area gets disabled and it is not allowing the user to enter anything. 

Please refer this visual - https://goo.gl/duvckW

-----

```
Test Environment : 

1. WP 5.1
2. Buddypress 4.2.0
3. rtMedia core - 4.5.6
```

**Comment by surajkrsingh** [comment] 2019-03-15 10:16
@kjnanda 
For the scenario-1
For posting something from activity both the things ( comment and media ) are not necessary so it quickly post when we click on t&c checkbox.

For the scenario-2
Textarea is not disable just added &nbsp; and the color of content is white so it not visible to us and look like disable.
you can write on textarea but it not visible because it's contents are white same as bg of textarea so after post you can see the contents.

**Comment by pooja-muchandikar** [comment] 2019-03-15 11:26
@surajkrsingh 
Cross-checked both the scenarios at my end and below are my findings. 
**For Scenario-1:** - yes its most likely that user might want to enter text and media in the activity feed. If wants to then, the user might add both contents ( media and text ) and then click on upload terms checkbox.
##

**For Scenario -2** - textarea doesn't get disabled but the text entered in the textarea is not visible and hence need to fix this issue. 
##

cc: @kjnanda

**Comment by surajkrsingh** [comment] 2019-03-18 06:08
PR: - https://github.com/rtMediaWP/rtMedia/pull/1306

**Comment by surajkrsingh** [comment] 2019-03-19 07:02
@pooja-muchandikar  @kjnanda 
In above issue the buddypress doesn't allow to keep empty to the textarea when we post something from activity post.
So before generated this issue we added space with transparent color so it looks like nothing in textarea (and disable too) so this thing create issue when user want to add something in textarea after upload a media.
For fixing this issue remove the white space before submit so user can enter some text and it doesn't look like disable

Note:- If user doesn't enter any text in textarea then after click on sumbit we forcefully put the white space so we can post.

**Comment by pooja-muchandikar** [comment] 2019-03-19 08:04
@surajkrsingh 
>For Scenario-1:
No need to fix anything because media and text both are not necessary to add even any thing from media or text (or both ) is sufficient to create post.
- Noted.
##

**Scenario 2**: Tested and with upload terms and direct upload enabled, able to enter text in textarea after uploading media. Previously text wasn't visible in the textarea, and the issue is been fixed now. 
##

But, while testing the fix added for **Scenario 2** found an issue with legacy template. Follow the below steps to reproduce the issue:
1. Disable upload terms options
2. Direct Upload should be enabled
3. Switch to the **Legacy template**
4. Now, since direct upload is enabled on uploading media, media should directly get uploaded. But media is not getting uploaded and an error message is displayed. _Note: Same works fine in Nouveau Template_

Refer to this visual: https://drive.google.com/file/d/1lE4giqtmRRenhkQd44Vpy6YvPeJ45orA/view

**Comment by surajkrsingh** [comment] 2019-03-19 11:12
PR:-https://github.com/rtMediaWP/rtMedia/pull/1314

**Comment by pooja-muchandikar** [comment] 2019-03-20 06:44
@surajkrsingh 

Testing is done and changes added works as expected.
```
Test Environment
WordPress: v5.1.1
rtMedia Core: Code from **pre-release** branch (v4.5.6)
BuddyPress: v4.2.0 ( Nouveau and Legacy template )
Themes: 2012, 2016, 2017 and 2019
```

**Comment by kjnanda** [comment] 2019-06-11 12:32
Tested with dev branch. Added changes are working as expected.

**Comment by kjnanda** [comment] 2019-06-12 13:01
Tested with master branch. Added changes are working as expected.

**Closed** 2019-06-13 12:32 UTC
Labels: Tested
