### ISSUE TITLE
the lightbox image is being cropped

### ISSUE THREAD

**Issue by MarrosSaldanha** [rtMediaWP/rtMedia#1394] opened 2019-06-26 03:13 UTC
the lightbox image is being cropped. What is the solution for it to appear without cuts? Is it possible to make the image stay in 100% of the lightbox, without appearing the black borders wrapped around the image?
I'm using the buddyboss theme.

<a href="https://ibb.co/hgtNhZQ"><img src="https://i.ibb.co/ZfkrtY4/errolightbox.jpg" alt="errolightbox" border="0"></a><br /><a target='_blank' href='https://aluminumsulfate.net/aluminum-oxide'>what is corundum used for</a><br />

<a href="https://ibb.co/xsvGLyg"><img src="https://i.ibb.co/TTXR2Z0/rtmeia.jpg" alt="rtmeia" border="0"></a>

<a href="https://ibb.co/1LswC9W"><img src="https://i.ibb.co/6mvfK4C/rtmeia-2.jpg" alt="rtmeia-2" border="0"></a>

**Comment by vishalkakadiya** [comment] 2019-07-25 09:04
@MarrosSaldanha
I try to reproduce this issue but can't able to, so can you provide below details that will help me to debug your issue more closely.
- Can you provide links where I can check that image or if possible can I get that image?
- Are you using any specific plugin for image thumbnails or plugin which is doing any type of image processing?

Thank you!

**Comment by MarrosSaldanha** [comment] 2019-07-29 19:49
Hi :) 
I’m very grateful to you for helping me

The link is this: https://www.arteexposta.com.br/members/arteexposta/media/
The green banner.


I deactivated all plugins and just left budypress and rtmedia on, and it didn't work.
my active plugins are these:

- WooCommerce Administration
- 
-  Akismet Anti-Spam
- 
-  Switching User
- 
-  ARG Multistep Checkout for WooCommerce
- 
-  Auto Image Attributes From Filename With Bulk Updater
- 
-  bbPress
- 
-  Beaver Builder Plugin (Pro Version)
- 
-  BP Force Profile Photo
- 
-  BP Post Front End Simple
- 
-  BP Profile Search
- 
-  BP Remove Profile Links
- 
-  BP xProfile Location
- 
-  BuddyBoss One Click Installer
- 
-  BuddyBoss Products Updater
- 
-  Buddypress
- 
-  BuddyPress Activity Bump
- 
-  BuddyPress Activity Comment Notifier
- 
-  BuddyPress edit activity
- 
-  BuddyPress Global Search
- 
-  BuddyPress Reorder Tabs
- 
-  BP Events Calendar
- 
-  Coming Soon Page & Maintenance Mode by SeedProd
- 
-  Custom JavaScript & CSS in Pages!
- 
-  Diagnosis and troubleshooting
- 
-  Duplicate Post
- 
-  Classic editor
- 
-  Epic News Elements
- 
-  Envato Elements
- 
-  Events Calendar PRO
- 
-  Awesome font
- 
-  Easy login Styler pro
- 
-  GEO my WP
- 
-  HelpDesk
- 
-  WordPress Importer
- 
-  Invisible reCaptcha
- 
-  Kaswara Modern VC Addons
- 
-  LoftLoader
- 
-  LS Buddypress Activity plus tabs extension
- 
-  Mailchimp for WordPress
- 
-  Media grid
- 
- 
-  Members
- 
-  Marketplace
- 
-  WC suppliers market
- 
-  The BuddyBlog
- 
-  Rank Math SEO
- 
-  Redux Framework
- 
-  rtMedia Likes
- 
-  RtMedia for WordPress, BuddyPress and bbPress
- 
-  rtMedia Restrictions
- 
-  rtMedia View Counter
- 
-  SG Optimizer
- 
-  Simple Custom CSS and JS
- 
-  Slick menu pro
- 
- 
-  Smush Pro
- 
- 
-  snip - The Rich Snippets & Structured Data Plugin
- 
- 
-  The Events Calendar
- 
-  The Events Calendar Shortcode and Templates
- 
-  Translation (Loco)
- 
-  Translator Revolution DropDown
- 
-  Ultimate Addons for WPBakery Page Builder
- 
-  Ultimate WooCommerce Filters
- 
-  UpdraftPlus - Backup / Restore
- 
-  User Menus
- 
-  WC Vendors Pro
- 
-  WooCommerce
- 
-  WooCommerce Blocks
- 
-  WooCommerce Post Office
- 
-  WooCommerce Extra Checkout Fields for Brazil
- 
-  WooCommerce Shipping Tracking
- 
-  WooCommerce Wirecard Brasil Official
- 
-  Wordfence Security
- 
-  Wordpress Automatic Plugin
- 
-  WP Content Crawler
- 
-  WP Downgrade | Specific Core Version
- 
-  WP Rollback
- 
-  WPBakery Page Builder

**Comment by MarrosSaldanha** [comment] 2019-08-08 16:13
I made a change by changing the wodpress media tools configuration. Then I used the Regenerate Thumbnails plugin to get the configuration again. Added in rtmedia value of 500 width and auto in height. I made a css edit of the black border that appeared at the bottom of the drawing. Not sure if you have a better css to shrink the black border and make the image bigger?

**Comment by kjnanda** [comment] 2019-08-09 03:58
@MarrosSaldanha Thanks for the detailed explanation. I will check with my team and will update you.

**Comment by thrijith** [comment] 2019-08-12 12:52
Hi @MarrosSaldanha,

I was unable to replicate the reported issue of image being cropped on a default theme ( twentyseventeen ), it seems that it is fixed on your [site](https://www.arteexposta.com.br/members/arteexposta/media/) now.

Unfortunately, we don't have a css to shrink borders as you expect, I see you have added custom css to reduce the black border but that might not be helpful when images have high resolutions, please ref this screencast. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13589980/62865920-4e849300-bd2d-11e9-91d8-8507bd8bfb03.gif)

**Comment by MarrosSaldanha** [comment] 2019-08-19 15:59
Thank's @thrijith 
I created more than 4 breakpoints to adjust the images.

**Comment by kjnanda** [comment] 2019-08-20 05:37
Hi @MarrosSaldanha,

Since the issue is fixed, I am closing this ticket.

**Closed by kjnanda** 2019-08-20 05:37 UTC
