### ISSUE TITLE
Issue after upload media.

### ISSUE THREAD

**Issue by yash7span** [rtMediaWP/rtMedia#1506] opened 2019-12-17 11:30 UTC
There is an issue occurring where when I upload an image using rtMedia to the activity stream (global or profile) when the image finishes uploading (but not posting) I’m getting a browser (Chrome) prompt saying “Leave site?” – then regardless of whether you click cancel or continue, the image doesn’t post.

This is not happening on the demo. I disabled all plugins, except BuddyPress & rtMedia and the issue was still happening. So I know it’s not a plugin conflict.

How can this be fixed? It’s incredibly annoying and unusable like this.

![image](https://user-images.githubusercontent.com/30891846/70991973-ad4c8580-20ee-11ea-8769-bac665bed990.png)

**Comment by kjnanda** [comment] 2019-12-17 11:41
Hi @yash7span,

Thank you for reporting the issue. My team will look into it and I will get back to you asap.

**Comment by kjnanda** [comment] 2019-12-18 12:21
Hi @yash7span 👋 

I hope you doing good!

My team tried to replicate the issue but we could not find any such occurrence of the issue. Can you please provide us some more information about the environment you are using?

**Comment by yash7span** [comment] 2019-12-18 13:10
Hi @kjnanda,

Thanks for the reply.

Do you need admin access to my environment??

**Comment by kjnanda** [comment] 2019-12-18 13:14
Yes, it would be great if you can share the `staging site` admin credentials. I would like to mention that my team may need to deactivate the currently active plugins and/or themes on your site to debug the cause of the issue.

Please confirm if this sounds good to you.

Looking forward to hearing back from you.

Regards,
Krupa

**Comment by kjnanda** [comment] 2019-12-18 13:19
Hey @yash7span I would like to request you to open a new support ticket on our support channel - https://rtmedia.io/support

Please share the credentials of the site over there only. 

Regards,
Krupa

**Comment by yash7span** [comment] 2019-12-18 13:20
Ok, I'll do it.

Thanks

**Comment by kjnanda** [comment] 2019-12-18 13:25
Thanks @yash7span 

I am closing this ticket from here and as per our discussion, we will further communicate over a support channel. Please draft your query and issue you are facing along with the credentials of staging site as requested.

Have a nice day!

Regards,
Krupa

**Comment by pooja-muchandikar** [comment] 2019-12-26 12:54
Released with 4.5.11 version

**Closed by pooja-muchandikar** 2019-12-26 12:54 UTC
