### ISSUE TITLE
My buddypress user's profile image cover are being changed when clicking on media 

### ISSUE THREAD

**Issue by juancito82** [rtMediaWP/rtMedia#1185] opened 2018-08-26 02:05 UTC

**Comment by kjnanda** [comment] 2018-08-27 09:49
Hi @juancito82, 

We tried to reproduce issue with profile pictures and cover images by clicking on different media files. However, it is working fine for us.

**Comment by pranali333** [comment] 2018-08-27 10:01
Hello @juancito82 ,

Please once try to troubleshoot the issue by:
- Activating any default theme of WordPress
- Deactivating other plugins except for rtMedia and BuddyPress

This way you can avoid possible conflicts.

Thanks,
Pranali

**Comment by juancito82** [comment] 2018-08-28 20:44
It is actually changing my buddypress settings if I click on media... currently my buddypress profiles have a round profile picture and rtmedia is changing it to square everytime the user clicks on media

**Comment by pranali333** [comment] 2018-08-29 08:26
Hello,

Did you give it a try to troubleshoot the issue by following the steps mentioned in my previous reply?

Regards,

**Comment by malavvasita** [comment] 2018-11-27 05:47
Hello @juancito82 ,

Good day.
Its been a long time we haven't heard from you.

Can you please confirm if you still face the issue or is it working fine for you now?
So that we conclude this ticket.

Thanks,
Malav

**Comment by kjnanda** [comment] 2019-11-26 17:44
Hi @juancito82, 

Can you please let us know if the issue got fixed?

Looking forward to hearing back from you.

Regards,
Krupa

**Comment by kjnanda** [comment] 2019-11-29 04:54
I believe the issue seems to be fixed at the customer's end. I am Closing this issue.

**Closed by kjnanda** 2019-11-29 04:54 UTC
