### ISSUE TITLE
[Activity Page] Issue with Max file size files

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/rtMedia#1402] opened 2019-07-05 08:40 UTC
Uploading the media file more than the accepted value then it shows the alert message which is correct! ✅ 

But at the same time if I click on the `Post Update` button without entering anything then it simply bypasses the media file and posts the empty activity which is not an ideal scenario! ❌ 

Please refer to this visual - https://drive.google.com/file/d/1TqPSHKijE5-UU-pfilX5Sols25yKnldY/view

----

```
Test Environment 

rtMedia V.4.5.7
BuddypPress V4.3.3 - Nouveau Template
WP V5.2.2
```

**Comment by thrijith** [comment] 2019-08-22 05:53
@kjnanda Unable to replicate this, please refer [this](https://drive.google.com/open?id=1naAo1kURo2GhvXdDJO_c2v3a3KsFABk9), I checked for `BuddypPress V4.3.3` but it doesn't seem to be a valid version, tested issue on `v4.3.0` was not able to replicate there too.

**Comment by kjnanda** [comment] 2019-10-07 07:11
@thrijith I checked it again at my end and found that the issue only appears for the BuddyPress Nouveau template pack. This works as expected with Legacy Template. I believe the empty content condition is being bypassed in the case of the Nouveau template and it adds extra space in the comment area to allow the user to post. This needs to be fixed.

Let me know if you have any queries to replicate this issue.

**Comment by vermadarsh** [comment] 2020-02-13 04:37
Hi @pooja-muchandikar

I tested this with the following environment details:
rtMedia: v4.5.11
BuddyPress: v5.1.2
WordPress: v5.3.2

I'm unable to replicate this issue, it seems everything works correctly.

**Comment by pooja-muchandikar** [comment] 2020-02-13 12:01
I have cross-checked the issue with BuddyPress legacy and nouveau template and couldn't reproduce this issue. 

Checked with BP older version `4.3.0` as well and it works as expected. 

Hence, closing this issue for now.

**Closed by pooja-muchandikar** 2020-02-13 12:01 UTC
Labels: bug
