### ISSUE TITLE
BP Nouveau profile media tab

### ISSUE THREAD

**Issue by franciscocervera** [rtMediaWP/rtMedia#1237] opened 2018-11-28 20:42 UTC
When media tab is selected in user's profile, the BP layout changes from Nouveau to Legacy.

**Profile view**
![image](https://user-images.githubusercontent.com/45086485/49180808-fcbce980-f312-11e8-8b77-b88e9527624d.png)

**Profile view (Media tab selected)**
![image](https://user-images.githubusercontent.com/45086485/49180854-1d853f00-f313-11e8-8e2b-09b9416a8094.png)

**Additional data:**

- WP Version: 4.9.8

- rtMedia Version: 4.5.4

- Used theme: Customify 0.2.5

**Comment by Febrezio** [comment] 2018-12-04 08:39
I'm seeing same issue. The "Media" profile template does not seem to be using the same styling as other Nouveau profile templates.

Also seeing theses related issues:

1. Profile picture issue ([1185](https://github.com/rtMediaWP/rtMedia/issues/1185)) where profile picture shows as square instead of expected circle.

2. Whenever I click on the Media tab, browser console shows rtMedia is trying to load "bp-legacy" CSS that does not exist (/wp-content/plugins/buddypress/bp-templates/bp-legacy/css/<my-theme>.min.css)...why is rtMedia loading "bp-legacy" style instead of "bp-nouveau"???

WordPress: 4.9.8
BuddyPress: 4.0.0
rtMedia: 4.5.4
Theme Name: Swifty (Boldgrid)
Theme Version: 1.2.1

**Comment by Febrezio** [comment] 2018-12-04 08:50
Actually I just checked browser console again and Item #2 above is big part of the problem. rtMedia is loading legacy buddypress style instead of Nouveau </wp-content/plugins/buddypress/bp-templates/bp-legacy/css/buddypress.min.css?ver=4.9.8>...I'm just not sure where in you code the legacy styles are being loaded.

...and somewhere rtMedia is probably also loading the wrong templates...or the rtMedia template is not compatible with BP 4.0.0

**Comment by Febrezio** [comment] 2018-12-04 09:58
There are quite a few typos in this [RTMedia.php block of code](https://github.com/rtMediaWP/rtMedia/blob/develop/app/main/RTMedia.php#L1273).

This is where **bp-nouveau** CSS should be loaded, correct?
I changed **bp-legacy** to **bp-nouveau** in the **bp-neavuaue-stylesheet-buddypress** URL and now the correct **BP** CSS is loading.
However, that does not resolve all template styling issues.

**Comment by franciscocervera** [comment] 2018-12-04 14:22
I have downgraded from BP 4.0.0 to 3.2.0 (mainly because it has a group management issue) but the problem persist. I'm pretty sure the origin of the bug is what you have already described on item #2.

**Comment by kjnanda** [comment] 2019-11-26 17:43
Hi Everyone!

It is been long time we have been heard from you. Can you please check and confirm if the issue is resolved?

Looking forward to hearing back from you guys.

Regards,

Krupa

**Comment by kjnanda** [comment] 2019-11-29 04:55
It seems like the issue is no more exists! I am closing this ticket.

**Closed by kjnanda** 2019-11-29 04:55 UTC

**Comment by jeffreyblueprint** [comment] 2020-01-27 17:16
Hi there. I'm also having this problem. When I'm on the Media nav tab, it's not Nouveau template that's loading. It makes other elements look all messy.
