### ISSUE TITLE
Error while deleting media from demo.rtmedia.io

### ISSUE THREAD

**Issue by nitun** [rtMediaWP/rtMedia#1324] opened 2019-04-04 10:51 UTC
When I tried to delete any media file from the WordPress dashboard media library, it's giving me an error 

![WordPress_›_Error](https://user-images.githubusercontent.com/1140051/55550379-b3800a80-56f5-11e9-9453-058e4407a133.png)

**Comment by ravatparmar** [comment] 2019-04-05 06:16
Thanks for the raising issue,

Issue Detail:

- This issue was there for the admin side only.
- Actually, When we delete media from backend at that time, media-related data from custom tables/core tables were got deleted by rtMedia.
- So attachment ( media ) post was deleted by rtMedia, and then WordPress trying to delete it again( and since data is already deleted it was giving an error. )   

Solution:

- I've added this check -> if we are in the backend and try to delete media at that time, rtMedia will delete only custom table data, and WordPress will delete core table data.

PR: #1326

**Comment by ravatparmar** [comment] 2019-04-05 06:33
Test Cases:

- Try to delete media from front end side media ( on activity, media tab, etc. )
- Delete media from the backend ( Everyplace where we allow the user to delete media. )
- Upload media from frontend and delete from the frontend / Do the same for the backend.
- Upload media from frontend and delete it from the backend.

**Comment by pooja-muchandikar** [comment] 2019-04-05 11:31
@ravatparmar 
Testing with the following test environment and looks fine now. 
```
Test Environment
WordPress: v5.1.1
rtMedia Core: v4.5.6 code from pre-release branch
BuddyPress: v4.2.0 ( nouveau and legacy
Themes: Default themes 2012, 2015, 2016, 2017 and 2019
```

Testing covered following points:
1. Uploaded media from media page and tried to delete from WP media library :white_check_mark: 
2. Uploaded media from media page and deleted from media gallery itself :white_check_mark: 
3. Checked media delete functionality from media lightbox and media single page :white_check_mark: 
4. Checked delete functionality from group media and group activity page :white_check_mark: 
5. Uploaded media in WP media library and performed bulk delete action :white_check_mark: 
6. Uploaded media in forum and checked delete functionality from WP media library :white_check_mark: 
7. Uploaded media in activity page and deleted it from WP media library :white_check_mark: 
8. Uploaded media in activity page and deleted it from activity page itself :white_check_mark:

**Comment by kjnanda** [comment] 2019-06-06 13:23
Media deleted from upload.php does not reflect in front end. 

@dharmin

**Comment by kjnanda** [comment] 2019-06-07 13:24
I have tested this functionality in my end. Please check the below points. 

The main agenda of this issue was - **delete functionality should work fine while deleting media from the back end.**
Which is working fine and there are no more errors coming while deleting media from the back end. ✅ 

Now as regression part, I need to test delete media functionality with all possible combinations and from all places where front end and back end delete operation should work in sync. Meaning is that if I delete any media from the front end it should delete the from the back end and reverse should also work fine.

Here, I am facing an issue. **While deleting media from the back end, it removes the respective entry from the front end. but deleting media from the front end, it doesn't remove the reference from back end.**

@dharmin Please do the needful.

CC @ravatparmar

**Comment by surajkrsingh** [comment] 2019-06-11 07:58
@ravatparmar @kjnanda @pooja-muchandikar 

I have made the changes and also tested given testcases on :- https://github.com/rtMediaWP/rtMedia/issues/1324#issuecomment-480242870

PR:-https://github.com/rtMediaWP/rtMedia/pull/1368

**Comment by kjnanda** [comment] 2019-07-23 11:45
The solution is not working. Please check this why is it behaving inconsistently! I am removing this issue from milestone

**Comment by kjnanda** [comment] 2019-11-22 09:43
I am not facing this anymore. Closing this issue

**Closed by kjnanda** 2019-11-22 09:43 UTC
Labels: bug
